#pragma once

#pragma region BONES_MASK
#define SKEL_ROOT 0x0
#define SKEL_Pelvis 0x2e28
#define SKEL_L_Thigh 0xe39f
#define SKEL_L_Calf 0xf9bb
#define SKEL_L_Foot 0x3779
#define SKEL_L_Toe0 0x83c
#define IK_L_Foot 0xfedd
#define PH_L_Foot 0xe175
#define MH_L_Knee 0xb3fe
#define SKEL_R_Thigh 0xca72
#define SKEL_R_Calf 0x9000
#define SKEL_R_Foot 0xcc4d
#define SKEL_R_Toe0 0x512d
#define IK_R_Foot 0x8aae
#define PH_R_Foot 0x60e6
#define MH_R_Knee 0x3fcf
#define RB_L_ThighRoll 0x5c57
#define RB_R_ThighRoll 0x192a
#define SKEL_Spine_Root 0xe0fd
#define SKEL_Spine0 0x5c01
#define SKEL_Spine1 0x60f0
#define SKEL_Spine2 0x60f1
#define SKEL_Spine3 0x60f2
#define SKEL_L_Clavicle 0xfcd9
#define SKEL_L_UpperArm 0xb1c5
#define SKEL_L_Forearm 0xeeeb
#define SKEL_L_Hand 0x49d9
#define SKEL_L_Finger00 0x67f2
#define SKEL_L_Finger01 0xff9
#define SKEL_L_Finger02 0xffa
#define SKEL_L_Finger10 0x67f3
#define SKEL_L_Finger11 0x1049
#define SKEL_L_Finger12 0x104a
#define SKEL_L_Finger20 0x67f4
#define SKEL_L_Finger21 0x1059
#define SKEL_L_Finger22 0x105a
#define SKEL_L_Finger30 0x67f5
#define SKEL_L_Finger31 0x1029
#define SKEL_L_Finger32 0x102a
#define SKEL_L_Finger40 0x67f6
#define SKEL_L_Finger41 0x1039
#define SKEL_L_Finger42 0x103a
#define PH_L_Hand 0xeb95
#define IK_L_Hand 0x8cbd
#define RB_L_ForeArmRoll 0xee4f
#define RB_L_ArmRoll 0x1470
#define MH_L_Elbow 0x58b7
#define SKEL_R_Clavicle 0x29d2
#define SKEL_R_UpperArm 0x9d4d
#define SKEL_R_Forearm 0x6e5c
#define SKEL_R_Hand 0xdead
#define SKEL_R_Finger00 0xe5f2
#define SKEL_R_Finger01 0xfa10
#define SKEL_R_Finger02 0xfa11
#define SKEL_R_Finger10 0xe5f3
#define SKEL_R_Finger11 0xfa60
#define SKEL_R_Finger12 0xfa61
#define SKEL_R_Finger20 0xe5f4
#define SKEL_R_Finger21 0xfa70
#define SKEL_R_Finger22 0xfa71
#define SKEL_R_Finger30 0xe5f5
#define SKEL_R_Finger31 0xfa40
#define SKEL_R_Finger32 0xfa41
#define SKEL_R_Finger40 0xe5f6
#define SKEL_R_Finger41 0xfa50
#define SKEL_R_Finger42 0xfa51
#define PH_R_Hand 0x6f06
#define IK_R_Hand 0x188e
#define RB_R_ForeArmRoll 0xab22
#define RB_R_ArmRoll 0x90ff
#define MH_R_Elbow 0xbb0
#define SKEL_Neck_1 0x9995
#define SKEL_Head 0x796e
#define IK_Head 0x322c
#define FACIAL_facialRoot 0xfe2c
#define FB_L_Brow_Out_000 0xe3db
#define FB_L_Lid_Upper_000 0xb2b6
#define FB_L_Eye_000 0x62ac
#define FB_L_CheekBone_000 0x542e
#define FB_L_Lip_Corner_000 0x74ac
#define FB_R_Lid_Upper_000 0xaa10
#define FB_R_Eye_000 0x6b52
#define FB_R_CheekBone_000 0x4b88
#define FB_R_Brow_Out_000 0x54c
#define FB_R_Lip_Corner_000 0x2ba6
#define FB_Brow_Centre_000 0x9149
#define FB_UpperLipRoot_000 0x4ed2
#define FB_UpperLip_000 0xf18f
#define FB_L_Lip_Top_000 0x4f37
#define FB_R_Lip_Top_000 0x4537
#define FB_Jaw_000 0xb4a0
#define FB_LowerLipRoot_000 0x4324
#define FB_LowerLip_000 0x508f
#define FB_L_Lip_Bot_000 0xb93b
#define FB_R_Lip_Bot_000 0xc33b
#define FB_Tongue_000 0xb987
#define RB_Neck_1 0x8b93
#define IK_Root 0xdd1c
#pragma endregion

enum BlipColor
{
	ColorWhite = 0,
	ColorRed = 1,
	ColorGreen = 2,
	ColorBlue = 3,
	ColorPlayer = 4,
	ColorYellow = 5,
	ColorPurple = 7,
	ColorVehicle = 38,
	ColorMichael = 42,
	ColorFranklin = 43,
	ColorTrevor = 44,
	ColorMissionRed = 49,
	ColorMissionVehicle = 54,
	ColorYellowMission = 66,
	ColorYellowMission2 = 60,
	ColorWaypoint = 84
};

enum BlipSprite
{
	SpriteStandard = 1,
	SpriteBig = 2,
	SpritePoliceOfficer = 3,
	SpritePoliceArea = 4,
	SpriteSquare = 5,
	SpritePlayer = 6,
	SpriteNorth = 7,
	SpriteWaypoint = 8,
	SpriteBigCircle = 9,
	SpriteBigCircleOutline = 10,
	SpriteArrowUpOutlined = 11,
	SpriteArrowDownOutlined = 12,
	SpriteArrowUp = 13,
	SpriteArrowDown = 14,
	SpritePoliceHelicopterAnimated = 15,
	SpriteJet = 16,
	SpriteNumber1 = 17,
	SpriteNumber2 = 18,
	SpriteNumber3 = 19,
	SpriteNumber4 = 20,
	SpriteNumber5 = 21,
	SpriteNumber6 = 22,
	SpriteNumber7 = 23,
	SpriteNumber8 = 24,
	SpriteNumber9 = 25,
	SpriteNumber10 = 26,
	SpriteGTAOCrew = 27,
	SpriteGTAOFriendly = 28,
	SpriteLift = 36,
	SpriteRaceFinish = 38,
	SpriteSafehouse = 40,
	SpritePoliceOfficer2 = 41,
	SpritePoliceCarDot = 42,
	SpritePoliceHelicopter = 43,
	SpriteChatBubble = 47,
	SpriteGarage2 = 50,
	SpriteDrugs = 51,
	SpriteStore = 52,
	SpritePoliceCar = 56,
	SpritePolicePlayer = 58,
	SpritePoliceStation = 60,
	SpriteHospital = 61,
	SpriteHelicopter = 64,
	SpriteStrangersAndFreaks = 65,
	SpriteArmoredTruck = 66,
	SpriteTowTruck = 68,
	SpriteBarber = 71,
	SpriteLosSantosCustoms = 72,
	SpriteClothes = 73,
	SpriteTattooParlor = 75,
	SpriteSimeon = 76,
	SpriteLester = 77,
	SpriteMichael = 78,
	SpriteTrevor = 79,
	SpriteRampage = 84,
	SpriteVinewoodTours = 85,
	SpriteLamar = 86,
	SpriteFranklin = 88,
	SpriteChinese = 89,
	SpriteAirport = 90,
	SpriteBar = 93,
	SpriteBaseJump = 94,
	SpriteCarWash = 100,
	SpriteComedyClub = 102,
	SpriteDart = 103,
	SpriteFIB = 106,
	SpriteDollarSign = 108,
	SpriteGolf = 109,
	SpriteAmmuNation = 110,
	SpriteExile = 112,
	SpriteShootingRange = 119,
	SpriteSolomon = 120,
	SpriteStripClub = 121,
	SpriteTennis = 122,
	SpriteTriathlon = 126,
	SpriteOffRoadRaceFinish = 127,
	SpriteKey = 134,
	SpriteMovieTheater = 135,
	SpriteMusic = 136,
	SpriteMarijuana = 140,
	SpriteHunting = 141,
	SpriteArmsTraffickingGround = 147,
	SpriteNigel = 149,
	SpriteAssaultRifle = 150,
	SpriteBat = 151,
	SpriteGrenade = 152,
	SpriteHealth = 153,
	SpriteKnife = 154,
	SpriteMolotov = 155,
	SpritePistol = 156,
	SpriteRPG = 157,
	SpriteShotgun = 158,
	SpriteSMG = 159,
	SpriteSniper = 160,
	SpriteSonicWave = 161,
	SpritePointOfInterest = 162,
	SpriteGTAOPassive = 163,
	SpriteGTAOUsingMenu = 164,
	SpriteLink = 171,
	SpriteMinigun = 173,
	SpriteGrenadeLauncher = 174,
	SpriteArmor = 175,
	SpriteCastle = 176,
	SpriteCamera = 184,
	SpriteHandcuffs = 188,
	SpriteYoga = 197,
	SpriteCab = 198,
	SpriteNumber11 = 199,
	SpriteNumber12 = 200,
	SpriteNumber13 = 201,
	SpriteNumber14 = 202,
	SpriteNumber15 = 203,
	SpriteNumber16 = 204,
	SpriteShrink = 205,
	SpriteEpsilon = 206,
	SpritePersonalVehicleCar = 225,
	SpritePersonalVehicleBike = 226,
	SpriteCustody = 237,
	SpriteArmsTraffickingAir = 251,
	SpriteFairground = 266,
	SpritePropertyManagement = 267,
	SpriteAltruist = 269,
	SpriteEnemy = 270,
	SpriteChop = 273,
	SpriteDead = 274,
	SpriteHooker = 279,
	SpriteFriend = 280,
	SpriteBountyHit = 303,
	SpriteGTAOMission = 304,
	SpriteGTAOSurvival = 305,
	SpriteCrateDrop = 306,
	SpritePlaneDrop = 307,
	SpriteSub = 308,
	SpriteRace = 309,
	SpriteDeathmatch = 310,
	SpriteArmWrestling = 311,
	SpriteAmmuNationShootingRange = 313,
	SpriteRaceAir = 314,
	SpriteRaceCar = 315,
	SpriteRaceSea = 316,
	SpriteGarbageTruck = 318,
	SpriteMotorCycle = 348,
	SpriteSafehouseForSale = 350,
	SpritePackage = 351,
	SpriteMartinMadrazo = 352,
	SpriteEnemyHelicopter = 353,
	SpriteBoost = 354,
	SpriteDevin = 355,
	SpriteMarina = 356,
	SpriteGarage = 357,
	SpriteGolfFlag = 358,
	SpriteHangar = 359,
	SpriteHelipad = 360,
	SpriteJerryCan = 361,
	SpriteMasks = 362,
	SpriteHeistSetup = 363,
	SpriteIncapacitated = 364,
	SpritePickupSpawn = 365,
	SpriteBoilerSuit = 366,
	SpriteCompleted = 367,
	SpriteRockets = 368,
	SpriteGarageForSale = 369,
	SpriteHelipadForSale = 370,
	SpriteMarinaForSale = 371,
	SpriteHangarForSale = 372,
	SpriteBusiness = 374,
	SpriteBusinessForSale = 375,
	SpriteRaceBike = 376,
	SpriteParachute = 377,
	SpriteTeamDeathmatch = 378,
	SpriteRaceFoot = 379,
	SpriteVehicleDeathmatch = 380,
	SpriteBarry = 381,
	SpriteDom = 382,
	SpriteMaryAnn = 383,
	SpriteCletus = 384,
	SpriteJosh = 385,
	SpriteMinute = 386,
	SpriteOmega = 387,
	SpriteTonya = 388,
	SpritePaparazzo = 389,
	SpriteCrosshair = 390,
	SpriteCreator = 398,
	SpriteCreatorDirection = 399,
	SpriteAbigail = 400,
	SpriteBlimp = 401,
	SpriteRepair = 402,
	SpriteTestosterone = 403,
	SpriteDinghy = 404,
	SpriteFanatic = 405,
	SpriteInformation = 407,
	SpriteCaptureBriefcase = 408,
	SpriteLastTeamStanding = 409,
	SpriteBoat = 410,
	SpriteCaptureHouse = 411,
	SpriteJerryCan2 = 415,
	SpriteRP = 416,
	SpriteGTAOPlayerSafehouse = 417,
	SpriteGTAOPlayerSafehouseDead = 418,
	SpriteCaptureAmericanFlag = 419,
	SpriteCaptureFlag = 420,
	SpriteTank = 421,
	SpriteHelicopterAnimated = 422,
	SpritePlane = 423,
	SpriteJet2 = 424,
	SpritePlayerNoColor = 425,
	SpriteGunCar = 426,
	SpriteSpeedboat = 427,
	SpriteHeist = 428,
	SpriteStopwatch = 430,
	SpriteDollarSignCircled = 431,
	SpriteCrosshair2 = 432,
	SpriteDollarSignSquared = 434,
};

enum ePedConfigFlags
{
	CPED_CONFIG_FLAG_CreatedByFactory = 0,
	CPED_CONFIG_FLAG_CanBeShotInVehicle = 1,
	CPED_CONFIG_FLAG_NoCriticalHits, // Detected by AC
	CPED_CONFIG_FLAG_DrownsInWater,
	CPED_CONFIG_FLAG_DrownsInSinkingVehicle,
	CPED_CONFIG_FLAG_DiesInstantlyWhenSwimming,
	CPED_CONFIG_FLAG_HasBulletProofVest,
	CPED_CONFIG_FLAG_UpperBodyDamageAnimsOnly,
	CPED_CONFIG_FLAG_NeverFallOffSkis,
	CPED_CONFIG_FLAG_NeverEverTargetThisPed,
	CPED_CONFIG_FLAG_ThisPedIsATargetPriority,
	CPED_CONFIG_FLAG_TargettableWithNoLos,
	CPED_CONFIG_FLAG_DoesntListenToPlayerGroupCommands,
	CPED_CONFIG_FLAG_NeverLeavesGroup,
	CPED_CONFIG_FLAG_DoesntDropWeaponsWhenDead,
	CPED_CONFIG_FLAG_SetDelayedWeaponAsCurrent,
	CPED_CONFIG_FLAG_KeepTasksAfterCleanUp,
	CPED_CONFIG_FLAG_BlockNonTemporaryEvents,
	CPED_CONFIG_FLAG_HasAScriptBrain,
	CPED_CONFIG_FLAG_WaitingForScriptBrainToLoad,
	CPED_CONFIG_FLAG_AllowMedicsToReviveMe,
	CPED_CONFIG_FLAG_MoneyHasBeenGivenByScript,
	CPED_CONFIG_FLAG_NotAllowedToCrouch,
	CPED_CONFIG_FLAG_DeathPickupsPersist,
	CPED_CONFIG_FLAG_IgnoreSeenMelee,
	CPED_CONFIG_FLAG_ForceDieIfInjured,
	CPED_CONFIG_FLAG_DontDragMeOutCar,
	CPED_CONFIG_FLAG_StayInCarOnJack,
	CPED_CONFIG_FLAG_ForceDieInCar,
	CPED_CONFIG_FLAG_GetOutUndriveableVehicle,
	CPED_CONFIG_FLAG_WillRemainOnBoatAfterMissionEnds,
	CPED_CONFIG_FLAG_DontStoreAsPersistent,
	CPED_CONFIG_FLAG_WillFlyThroughWindscreen,
	CPED_CONFIG_FLAG_DieWhenRagdoll,
	CPED_CONFIG_FLAG_HasHelmet,
	CPED_CONFIG_FLAG_UseHelmet,
	CPED_CONFIG_FLAG_DontTakeOffHelmet,
	CPED_CONFIG_FLAG_HideInCutscene,
	CPED_CONFIG_FLAG_PedIsEnemyToPlayer,
	CPED_CONFIG_FLAG_DisableEvasiveDives,
	CPED_CONFIG_FLAG_PedGeneratesDeadBodyEvents,
	CPED_CONFIG_FLAG_DontAttackPlayerWithoutWantedLevel,
	CPED_CONFIG_FLAG_DontInfluenceWantedLevel,
	CPED_CONFIG_FLAG_DisablePlayerLockon,
	CPED_CONFIG_FLAG_DisableLockonToRandomPeds,
	CPED_CONFIG_FLAG_AllowLockonToFriendlyPlayers,
	CPED_CONFIG_FLAG_DisableHornAudioWhenDead,
	CPED_CONFIG_FLAG_PedBeingDeleted,
	CPED_CONFIG_FLAG_BlockWeaponSwitching,
	CPED_CONFIG_FLAG_BlockGroupPedAimedAtResponse,
	CPED_CONFIG_FLAG_WillFollowLeaderAnyMeans,
	CPED_CONFIG_FLAG_BlippedByScript,
	CPED_CONFIG_FLAG_DrawRadarVisualField,
	CPED_CONFIG_FLAG_StopWeaponFiringOnImpact,
	CPED_CONFIG_FLAG_DissableAutoFallOffTests,
	CPED_CONFIG_FLAG_SteerAroundDeadBodies,
	CPED_CONFIG_FLAG_ConstrainToNavMesh,
	CPED_CONFIG_FLAG_SyncingAnimatedProps,
	CPED_CONFIG_FLAG_IsFiring,
	CPED_CONFIG_FLAG_WasFiring,
	CPED_CONFIG_FLAG_IsStanding,
	CPED_CONFIG_FLAG_WasStanding,
	CPED_CONFIG_FLAG_InVehicle,
	CPED_CONFIG_FLAG_OnMount,
	CPED_CONFIG_FLAG_AttachedToVehicle,
	CPED_CONFIG_FLAG_IsSwimming,
	CPED_CONFIG_FLAG_WasSwimming,
	CPED_CONFIG_FLAG_IsSkiing,
	CPED_CONFIG_FLAG_IsSitting,
	CPED_CONFIG_FLAG_KilledByStealth,
	CPED_CONFIG_FLAG_KilledByTakedown,
	CPED_CONFIG_FLAG_Knockedout,
	CPED_CONFIG_FLAG_ClearRadarBlipOnDeath,
	CPED_CONFIG_FLAG_JustGotOffTrain,
	CPED_CONFIG_FLAG_JustGotOnTrain,
	CPED_CONFIG_FLAG_UsingCoverPoint,
	CPED_CONFIG_FLAG_IsInTheAir,
	CPED_CONFIG_FLAG_KnockedUpIntoAir,
	CPED_CONFIG_FLAG_IsAimingGun,
	CPED_CONFIG_FLAG_HasJustLeftCar,
	CPED_CONFIG_FLAG_TargetWhenInjuredAllowed,
	CPED_CONFIG_FLAG_CurrLeftFootCollNM,
	CPED_CONFIG_FLAG_PrevLeftFootCollNM,
	CPED_CONFIG_FLAG_CurrRightFootCollNM,
	CPED_CONFIG_FLAG_PrevRightFootCollNM,
	CPED_CONFIG_FLAG_HasBeenBumpedInCar,
	CPED_CONFIG_FLAG_InWaterTaskQuitToClimbLadder,
	CPED_CONFIG_FLAG_NMTwoHandedWeaponBothHandsConstrained,
	CPED_CONFIG_FLAG_CreatedBloodPoolTimer,
	CPED_CONFIG_FLAG_DontActivateRagdollFromAnyPedImpact,
	CPED_CONFIG_FLAG_GroupPedFailedToEnterCover,
	CPED_CONFIG_FLAG_AlreadyChattedOnPhone,
	CPED_CONFIG_FLAG_AlreadyReactedToPedOnRoof,
	CPED_CONFIG_FLAG_ForcePedLoadCover,
	CPED_CONFIG_FLAG_BlockCoweringInCover,
	CPED_CONFIG_FLAG_BlockPeekingInCover,
	CPED_CONFIG_FLAG_JustLeftCarNotCheckedForDoors,
	CPED_CONFIG_FLAG_VaultFromCover,
	CPED_CONFIG_FLAG_AutoConversationLookAts,
	CPED_CONFIG_FLAG_UsingCrouchedPedCapsule,
	CPED_CONFIG_FLAG_HasDeadPedBeenReported,
	CPED_CONFIG_FLAG_ForcedAim,
	CPED_CONFIG_FLAG_SteersAroundPeds,
	CPED_CONFIG_FLAG_SteersAroundObjects,
	CPED_CONFIG_FLAG_OpenDoorArmIK,
	CPED_CONFIG_FLAG_ForceReload,
	CPED_CONFIG_FLAG_DontActivateRagdollFromVehicleImpact,
	CPED_CONFIG_FLAG_DontActivateRagdollFromBulletImpact,
	CPED_CONFIG_FLAG_DontActivateRagdollFromExplosions,
	CPED_CONFIG_FLAG_DontActivateRagdollFromFire,
	CPED_CONFIG_FLAG_DontActivateRagdollFromElectrocution,
	CPED_CONFIG_FLAG_IsBeingDraggedToSafety,
	CPED_CONFIG_FLAG_HasBeenDraggedToSafety,
	CPED_CONFIG_FLAG_KeepWeaponHolsteredUnlessFired,
	CPED_CONFIG_FLAG_ForceScriptControlledKnockout,
	CPED_CONFIG_FLAG_FallOutOfVehicleWhenKilled,
	CPED_CONFIG_FLAG_GetOutBurningVehicle,
	CPED_CONFIG_FLAG_BumpedByPlayer,
	CPED_CONFIG_FLAG_RunFromFiresAndExplosions,
	CPED_CONFIG_FLAG_TreatAsPlayerDuringTargeting,
	CPED_CONFIG_FLAG_IsHandCuffed,
	CPED_CONFIG_FLAG_IsAnkleCuffed,
	CPED_CONFIG_FLAG_DisableMelee,
	CPED_CONFIG_FLAG_DisableUnarmedDrivebys,
	CPED_CONFIG_FLAG_JustGetsPulledOutWhenElectrocuted,
	CPED_CONFIG_FLAG_UNUSED_REPLACE_ME,
	CPED_CONFIG_FLAG_WillNotHotwireLawEnforcementVehicle,
	CPED_CONFIG_FLAG_WillCommandeerRatherThanJack,
	CPED_CONFIG_FLAG_CanBeAgitated,
	CPED_CONFIG_FLAG_ForcePedToFaceLeftInCover,
	CPED_CONFIG_FLAG_ForcePedToFaceRightInCover,
	CPED_CONFIG_FLAG_BlockPedFromTurningInCover,
	CPED_CONFIG_FLAG_KeepRelationshipGroupAfterCleanUp,
	CPED_CONFIG_FLAG_ForcePedToBeDragged,
	CPED_CONFIG_FLAG_PreventPedFromReactingToBeingJacked,
	CPED_CONFIG_FLAG_IsScuba,
	CPED_CONFIG_FLAG_WillArrestRatherThanJack,
	CPED_CONFIG_FLAG_RemoveDeadExtraFarAway,
	CPED_CONFIG_FLAG_RidingTrain,
	CPED_CONFIG_FLAG_ArrestResult,
	CPED_CONFIG_FLAG_CanAttackFriendly,
	CPED_CONFIG_FLAG_WillJackAnyPlayer,
	CPED_CONFIG_FLAG_BumpedByPlayerVehicle,
	CPED_CONFIG_FLAG_DodgedPlayerVehicle,
	CPED_CONFIG_FLAG_WillJackWantedPlayersRatherThanStealCar,
	CPED_CONFIG_FLAG_NoCopWantedAggro,
	CPED_CONFIG_FLAG_DisableLadderClimbing,
	CPED_CONFIG_FLAG_StairsDetected,
	CPED_CONFIG_FLAG_SlopeDetected,
	CPED_CONFIG_FLAG_HelmetHasBeenShot,
	CPED_CONFIG_FLAG_CowerInsteadOfFlee,
	CPED_CONFIG_FLAG_CanActivateRagdollWhenVehicleUpsideDown,
	CPED_CONFIG_FLAG_AlwaysRespondToCriesForHelp,
	CPED_CONFIG_FLAG_DisableBloodPoolCreation,
	CPED_CONFIG_FLAG_ShouldFixIfNoCollision,
	CPED_CONFIG_FLAG_CanPerformArrest,
	CPED_CONFIG_FLAG_CanPerformUncuff,
	CPED_CONFIG_FLAG_CanBeArrested,
	CPED_CONFIG_FLAG_MoverConstrictedByOpposingCollisions,
	CPED_CONFIG_FLAG_PlayerPreferFrontSeatMP,
	CPED_CONFIG_FLAG_DontActivateRagdollFromImpactObject,
	CPED_CONFIG_FLAG_DontActivateRagdollFromMelee,
	CPED_CONFIG_FLAG_DontActivateRagdollFromWaterJet,
	CPED_CONFIG_FLAG_DontActivateRagdollFromDrowning,
	CPED_CONFIG_FLAG_DontActivateRagdollFromFalling,
	CPED_CONFIG_FLAG_DontActivateRagdollFromRubberBullet,
	CPED_CONFIG_FLAG_IsInjured,
	CPED_CONFIG_FLAG_DontEnterVehiclesInPlayersGroup,
	CPED_CONFIG_FLAG_SwimmingTasksRunning,
	CPED_CONFIG_FLAG_PreventAllMeleeTaunts,
	CPED_CONFIG_FLAG_ForceDirectEntry,
	CPED_CONFIG_FLAG_AlwaysSeeApproachingVehicles,
	CPED_CONFIG_FLAG_CanDiveAwayFromApproachingVehicles,
	CPED_CONFIG_FLAG_AllowPlayerToInterruptVehicleEntryExit,
	CPED_CONFIG_FLAG_OnlyAttackLawIfPlayerIsWanted,
	CPED_CONFIG_FLAG_PlayerInContactWithKinematicPed,
	CPED_CONFIG_FLAG_PlayerInContactWithSomethingOtherThanKinematicPed,
	CPED_CONFIG_FLAG_PedsJackingMeDontGetIn,
	CPED_CONFIG_FLAG_AdditionalRappellingPed,
	CPED_CONFIG_FLAG_PedIgnoresAnimInterruptEvents,
	CPED_CONFIG_FLAG_IsInCustody,
	CPED_CONFIG_FLAG_ForceStandardBumpReactionThresholds,
	CPED_CONFIG_FLAG_LawWillOnlyAttackIfPlayerIsWanted,
	CPED_CONFIG_FLAG_IsAgitated,
	CPED_CONFIG_FLAG_PreventAutoShuffleToDriversSeat,
	CPED_CONFIG_FLAG_UseKinematicModeWhenStationary,
	CPED_CONFIG_FLAG_EnableWeaponBlocking,
	CPED_CONFIG_FLAG_HasHurtStarted,
	CPED_CONFIG_FLAG_DisableHurt,
	CPED_CONFIG_FLAG_PlayerIsWeird,
	CPED_CONFIG_FLAG_PedHadPhoneConversation,
	CPED_CONFIG_FLAG_BeganCrossingRoad,
	CPED_CONFIG_FLAG_WarpIntoLeadersVehicle,
	CPED_CONFIG_FLAG_DoNothingWhenOnFootByDefault,
	CPED_CONFIG_FLAG_UsingScenario,
	CPED_CONFIG_FLAG_VisibleOnScreen,
	CPED_CONFIG_FLAG_DontCollideWithKinematic,
	CPED_CONFIG_FLAG_ActivateOnSwitchFromLowPhysicsLod,
	CPED_CONFIG_FLAG_DontActivateRagdollOnPedCollisionWhenDead,
	CPED_CONFIG_FLAG_DontActivateRagdollOnVehicleCollisionWhenDead,
	CPED_CONFIG_FLAG_HasBeenInArmedCombat,
	CPED_CONFIG_FLAG_UseDiminishingAmmoRate,
	CPED_CONFIG_FLAG_Avoidance_Ignore_All,
	CPED_CONFIG_FLAG_Avoidance_Ignored_by_All,
	CPED_CONFIG_FLAG_Avoidance_Ignore_Group1,
	CPED_CONFIG_FLAG_Avoidance_Member_of_Group1,
	CPED_CONFIG_FLAG_ForcedToUseSpecificGroupSeatIndex,
	CPED_CONFIG_FLAG_LowPhysicsLodMayPlaceOnNavMesh,
	CPED_CONFIG_FLAG_DisableExplosionReactions,
	CPED_CONFIG_FLAG_DodgedPlayer,
	CPED_CONFIG_FLAG_WaitingForPlayerControlInterrupt,
	CPED_CONFIG_FLAG_ForcedToStayInCover,
	CPED_CONFIG_FLAG_GeneratesSoundEvents,
	CPED_CONFIG_FLAG_ListensToSoundEvents,
	CPED_CONFIG_FLAG_AllowToBeTargetedInAVehicle,
	CPED_CONFIG_FLAG_WaitForDirectEntryPointToBeFreeWhenExiting,
	CPED_CONFIG_FLAG_OnlyRequireOnePressToExitVehicle,
	CPED_CONFIG_FLAG_ForceExitToSkyDive,
	CPED_CONFIG_FLAG_SteersAroundVehicles,
	CPED_CONFIG_FLAG_AllowPedInVehiclesOverrideTaskFlags,
	CPED_CONFIG_FLAG_DontEnterLeadersVehicle,
	CPED_CONFIG_FLAG_DisableExitToSkyDive,
	CPED_CONFIG_FLAG_ScriptHasDisabledCollision,
	CPED_CONFIG_FLAG_UseAmbientModelScaling,
	CPED_CONFIG_FLAG_DontWatchFirstOnNextHurryAway,
	CPED_CONFIG_FLAG_DisablePotentialToBeWalkedIntoResponse,
	CPED_CONFIG_FLAG_DisablePedAvoidance,
	CPED_CONFIG_FLAG_ForceRagdollUponDeath,
	CPED_CONFIG_FLAG_CanLosePropsOnDamage,
	CPED_CONFIG_FLAG_DisablePanicInVehicle,
	CPED_CONFIG_FLAG_AllowedToDetachTrailer,
	CPED_CONFIG_FLAG_HasShotBeenReactedToFromFront,
	CPED_CONFIG_FLAG_HasShotBeenReactedToFromBack,
	CPED_CONFIG_FLAG_HasShotBeenReactedToFromLeft,
	CPED_CONFIG_FLAG_HasShotBeenReactedToFromRight,
	CPED_CONFIG_FLAG_AllowBlockDeadPedRagdollActivation,
	CPED_CONFIG_FLAG_IsHoldingProp,
	CPED_CONFIG_FLAG_BlocksPathingWhenDead,
	CPED_CONFIG_FLAG_ForcePlayNormalScenarioExitOnNextScriptCommand,
	CPED_CONFIG_FLAG_ForcePlayImmediateScenarioExitOnNextScriptCommand,
	CPED_CONFIG_FLAG_ForceSkinCharacterCloth,
	CPED_CONFIG_FLAG_LeaveEngineOnWhenExitingVehicles,
	CPED_CONFIG_FLAG_PhoneDisableTextingAnimations,
	CPED_CONFIG_FLAG_PhoneDisableTalkingAnimations,
	CPED_CONFIG_FLAG_PhoneDisableCameraAnimations,
	CPED_CONFIG_FLAG_DisableBlindFiringInShotReactions,
	CPED_CONFIG_FLAG_AllowNearbyCoverUsage,
	CPED_CONFIG_FLAG_InStrafeTransition,
	CPED_CONFIG_FLAG_CanPlayInCarIdles,
	CPED_CONFIG_FLAG_CanAttackNonWantedPlayerAsLaw,
	CPED_CONFIG_FLAG_WillTakeDamageWhenVehicleCrashes,
	CPED_CONFIG_FLAG_AICanDrivePlayerAsRearPassenger,
	CPED_CONFIG_FLAG_PlayerCanJackFriendlyPlayers,
	CPED_CONFIG_FLAG_OnStairs,
	CPED_CONFIG_FLAG_SimulatingAiming,
	CPED_CONFIG_FLAG_AIDriverAllowFriendlyPassengerSeatEntry,
	CPED_CONFIG_FLAG_ParentCarIsBeingRemoved,
	CPED_CONFIG_FLAG_AllowMissionPedToUseInjuredMovement,
	CPED_CONFIG_FLAG_CanLoseHelmetOnDamage,
	CPED_CONFIG_FLAG_NeverDoScenarioExitProbeChecks,
	CPED_CONFIG_FLAG_SuppressLowLODRagdollSwitchWhenCorpseSettles,
	CPED_CONFIG_FLAG_PreventUsingLowerPrioritySeats,
	CPED_CONFIG_FLAG_JustLeftVehicleNeedsReset,
	CPED_CONFIG_FLAG_TeleportIfCantReachPlayer,
	CPED_CONFIG_FLAG_PedsInVehiclePositionNeedsReset,
	CPED_CONFIG_FLAG_PedsFullyInSeat,
	CPED_CONFIG_FLAG_AllowPlayerLockOnIfFriendly,
	CPED_CONFIG_FLAG_UseCameraHeadingForDesiredDirectionLockOnTest,
	CPED_CONFIG_FLAG_TeleportToLeaderVehicle,
	CPED_CONFIG_FLAG_Avoidance_Ignore_WeirdPedBuffer,
	CPED_CONFIG_FLAG_OnStairSlope,
	CPED_CONFIG_FLAG_HasPlayedNMGetup,
	CPED_CONFIG_FLAG_DontBlipCop,
	CPED_CONFIG_FLAG_SpawnedAtExtendedRangeScenario,
	CPED_CONFIG_FLAG_WalkAlongsideLeaderWhenClose,
	CPED_CONFIG_FLAG_KillWhenTrapped,
	CPED_CONFIG_FLAG_EdgeDetected,
	CPED_CONFIG_FLAG_AlwaysWakeUpPhysicsOfIntersectedPeds,
	CPED_CONFIG_FLAG_EquippedAmbientLoadOutWeapon,
	CPED_CONFIG_FLAG_AvoidTearGas,
	CPED_CONFIG_FLAG_StoppedSpeechUponFreezing,
	CPED_CONFIG_FLAG_DisableGoToWritheWhenInjured,
	CPED_CONFIG_FLAG_OnlyUseForcedSeatWhenEnteringHeliInGroup,
	CPED_CONFIG_FLAG_ThrownFromVehicleDueToExhaustion,
	CPED_CONFIG_FLAG_UpdateEnclosedSearchRegion,
	CPED_CONFIG_FLAG_DisableWeirdPedEvents,
	CPED_CONFIG_FLAG_ShouldChargeNow,
	CPED_CONFIG_FLAG_RagdollingOnBoat,
	CPED_CONFIG_FLAG_HasBrandishedWeapon,
	CPED_CONFIG_FLAG_AllowMinorReactionsAsMissionPed,
	CPED_CONFIG_FLAG_BlockDeadBodyShockingEventsWhenDead,
	CPED_CONFIG_FLAG_PedHasBeenSeen,
	CPED_CONFIG_FLAG_PedIsInReusePool,
	CPED_CONFIG_FLAG_PedWasReused,
	CPED_CONFIG_FLAG_DisableShockingEvents,
	CPED_CONFIG_FLAG_MovedUsingLowLodPhysicsSinceLastActive,
	CPED_CONFIG_FLAG_NeverReactToPedOnRoof,
	CPED_CONFIG_FLAG_ForcePlayFleeScenarioExitOnNextScriptCommand,
	CPED_CONFIG_FLAG_JustBumpedIntoVehicle,
	CPED_CONFIG_FLAG_DisableShockingDrivingOnPavementEvents,
	CPED_CONFIG_FLAG_ShouldThrowSmokeNow,
	CPED_CONFIG_FLAG_DisablePedConstraints,
	CPED_CONFIG_FLAG_ForceInitialPeekInCover,
	CPED_CONFIG_FLAG_CreatedByDispatch,
	CPED_CONFIG_FLAG_PointGunLeftHandSupporting,
	CPED_CONFIG_FLAG_DisableJumpingFromVehiclesAfterLeader,
	CPED_CONFIG_FLAG_DontActivateRagdollFromPlayerPedImpact,
	CPED_CONFIG_FLAG_DontActivateRagdollFromAiRagdollImpact,
	CPED_CONFIG_FLAG_DontActivateRagdollFromPlayerRagdollImpact,
	CPED_CONFIG_FLAG_DisableQuadrupedSpring,
	CPED_CONFIG_FLAG_IsInCluster,
	CPED_CONFIG_FLAG_ShoutToGroupOnPlayerMelee,
	CPED_CONFIG_FLAG_IgnoredByAutoOpenDoors,
	CPED_CONFIG_FLAG_PreferInjuredGetup,
	CPED_CONFIG_FLAG_ForceIgnoreMeleeActiveCombatant,
	CPED_CONFIG_FLAG_CheckLoSForSoundEvents,
	CPED_CONFIG_FLAG_JackedAbandonedCar,
	CPED_CONFIG_FLAG_CanSayFollowedByPlayerAudio,
	CPED_CONFIG_FLAG_ActivateRagdollFromMinorPlayerContact,
	CPED_CONFIG_FLAG_HasPortablePickupAttached,
	CPED_CONFIG_FLAG_ForcePoseCharacterCloth,
	CPED_CONFIG_FLAG_HasClothCollisionBounds,
	CPED_CONFIG_FLAG_HasHighHeels,
	CPED_CONFIG_FLAG_TreatAsAmbientPedForDriverLockOn,
	CPED_CONFIG_FLAG_DontBehaveLikeLaw,
	CPED_CONFIG_FLAG_SpawnedAtScenario,
	CPED_CONFIG_FLAG_DisablePoliceInvestigatingBody,
	CPED_CONFIG_FLAG_DisableWritheShootFromGround,
	CPED_CONFIG_FLAG_LowerPriorityOfWarpSeats,
	CPED_CONFIG_FLAG_DisableTalkTo,
	CPED_CONFIG_FLAG_DontBlip,
	CPED_CONFIG_FLAG_IsSwitchingWeapon,
	CPED_CONFIG_FLAG_IgnoreLegIkRestrictions,
	CPED_CONFIG_FLAG_ScriptForceNoTimesliceIntelligenceUpdate,
	CPED_CONFIG_FLAG_JackedOutOfMyVehicle,
	CPED_CONFIG_FLAG_WentIntoCombatAfterBeingJacked,
	CPED_CONFIG_FLAG_DontActivateRagdollForVehicleGrab,
	CPED_CONFIG_FLAG_ForcePackageCharacterCloth,
	CPED_CONFIG_FLAG_DontRemoveWithValidOrder,
	CPED_CONFIG_FLAG_AllowTaskDoNothingTimeslicing,
	CPED_CONFIG_FLAG_ForcedToStayInCoverDueToPlayerSwitch,
	CPED_CONFIG_FLAG_ForceProneCharacterCloth,
	CPED_CONFIG_FLAG_NotAllowedToJackAnyPlayers,
	CPED_CONFIG_FLAG_InToStrafeTransition,
	CPED_CONFIG_FLAG_KilledByStandardMelee,
	CPED_CONFIG_FLAG_AlwaysLeaveTrainUponArrival,
	CPED_CONFIG_FLAG_ForcePlayDirectedNormalScenarioExitOnNextScriptCommand,
	CPED_CONFIG_FLAG_OnlyWritheFromWeaponDamage,
	CPED_CONFIG_FLAG_UseSloMoBloodVfx,
	CPED_CONFIG_FLAG_EquipJetpack,
	CPED_CONFIG_FLAG_PreventDraggedOutOfCarThreatResponse,
	CPED_CONFIG_FLAG_ScriptHasCompletelyDisabledCollision,
	CPED_CONFIG_FLAG_NeverDoScenarioNavChecks,
	CPED_CONFIG_FLAG_ForceSynchronousScenarioExitChecking,
	CPED_CONFIG_FLAG_ThrowingGrenadeWhileAiming,
	CPED_CONFIG_FLAG_HeadbobToRadioEnabled,
	CPED_CONFIG_FLAG_ForceDeepSurfaceCheck,
	CPED_CONFIG_FLAG_DisableDeepSurfaceAnims,
	CPED_CONFIG_FLAG_DontBlipNotSynced,
	CPED_CONFIG_FLAG_IsDuckingInVehicle,
	CPED_CONFIG_FLAG_PreventAutoShuffleToTurretSeat,
	CPED_CONFIG_FLAG_DisableEventInteriorStatusCheck,
	CPED_CONFIG_FLAG_HasReserveParachute,
	CPED_CONFIG_FLAG_UseReserveParachute,
	CPED_CONFIG_FLAG_TreatDislikeAsHateWhenInCombat,
	CPED_CONFIG_FLAG_OnlyUpdateTargetWantedIfSeen,
	CPED_CONFIG_FLAG_AllowAutoShuffleToDriversSeat,
	CPED_CONFIG_FLAG_DontActivateRagdollFromSmokeGrenade,
	CPED_CONFIG_FLAG_LinkMBRToOwnerOnChain,
	CPED_CONFIG_FLAG_AmbientFriendBumpedByPlayer,
	CPED_CONFIG_FLAG_AmbientFriendBumpedByPlayerVehicle,
	CPED_CONFIG_FLAG_InFPSUnholsterTransition,
	CPED_CONFIG_FLAG_PreventReactingToSilencedCloneBullets,
	CPED_CONFIG_FLAG_DisableInjuredCryForHelpEvents,
	CPED_CONFIG_FLAG_NeverLeaveTrain,
	CPED_CONFIG_FLAG_DontDropJetpackOnDeath,
	CPED_CONFIG_FLAG_UseFPSUnholsterTransitionDuringCombatRoll,
	CPED_CONFIG_FLAG_ExitingFPSCombatRoll,
	CPED_CONFIG_FLAG_ScriptHasControlOfPlayer,
	CPED_CONFIG_FLAG_PlayFPSIdleFidgetsForProjectile,
	CPED_CONFIG_FLAG_DisableAutoEquipHelmetsInBikes,
	CPED_CONFIG_FLAG_DisableAutoEquipHelmetsInAircraft,
	CPED_CONFIG_FLAG_WasPlayingFPSGetup,
	CPED_CONFIG_FLAG_WasPlayingFPSMeleeActionResult,
	CPED_CONFIG_FLAG_PreferNoPriorityRemoval,
	CPED_CONFIG_FLAG_FPSFidgetsAbortedOnFire,
	CPED_CONFIG_FLAG_ForceFPSIKWithUpperBodyAnim,
	CPED_CONFIG_FLAG_SwitchingCharactersInFirstPerson,
	CPED_CONFIG_FLAG_IsClimbingLadder,
	CPED_CONFIG_FLAG_HasBareFeet,
	CPED_CONFIG_FLAG_UNUSED_REPLACE_ME_2,
	CPED_CONFIG_FLAG_GoOnWithoutVehicleIfItIsUnableToGetBackToRoad,
	CPED_CONFIG_FLAG_BlockDroppingHealthSnacksOnDeath,
	CPED_CONFIG_FLAG_ResetLastVehicleOnVehicleExit,
	CPED_CONFIG_FLAG_ForceThreatResponseToNonFriendToFriendMeleeActions,
	CPED_CONFIG_FLAG_DontRespondToRandomPedsDamage,
	CPED_CONFIG_FLAG_AllowContinuousThreatResponseWantedLevelUpdates,
	CPED_CONFIG_FLAG_KeepTargetLossResponseOnCleanup,
	CPED_CONFIG_FLAG_PlayersDontDragMeOutOfCar,
	CPED_CONFIG_FLAG_BroadcastRepondedToThreatWhenGoingToPointShooting,
	CPED_CONFIG_FLAG_IgnorePedTypeForIsFriendlyWith,
	CPED_CONFIG_FLAG_TreatNonFriendlyAsHateWhenInCombat,
	CPED_CONFIG_FLAG_DontLeaveVehicleIfLeaderNotInVehicle,
	CPED_CONFIG_FLAG_ChangeFromPermanentToAmbientPopTypeOnMigration,
	CPED_CONFIG_FLAG_AllowMeleeReactionIfMeleeProofIsOn,
	CPED_CONFIG_FLAG_UsingLowriderLeans,
	CPED_CONFIG_FLAG_UsingAlternateLowriderLeans,
	CPED_CONFIG_FLAG_UseNormalExplosionDamageWhenBlownUpInVehicle,
	CPED_CONFIG_FLAG_DisableHomingMissileLockForVehiclePedInside,
	CPED_CONFIG_FLAG_DisableTakeOffScubaGear,
	CPED_CONFIG_FLAG_IgnoreMeleeFistWeaponDamageMult,
	CPED_CONFIG_FLAG_LawPedsCanFleeFromNonWantedPlayer,
	CPED_CONFIG_FLAG_ForceBlipSecurityPedsIfPlayerIsWanted,
	CPED_CONFIG_FLAG_IsHolsteringWeapon,
	CPED_CONFIG_FLAG_UseGoToPointForScenarioNavigation,
	CPED_CONFIG_FLAG_DontClearLocalPassengersWantedLevel,
	CPED_CONFIG_FLAG_BlockAutoSwapOnWeaponPickups,
	CPED_CONFIG_FLAG_ThisPedIsATargetPriorityForAI,
	CPED_CONFIG_FLAG_IsSwitchingHelmetVisor,
	CPED_CONFIG_FLAG_ForceHelmetVisorSwitch,
	CPED_CONFIG_FLAG_IsPerformingVehicleMelee,
	CPED_CONFIG_FLAG_UseOverrideFootstepPtFx,
	CPED_CONFIG_FLAG_DisableVehicleCombat,
	CPED_CONFIG_FLAG_TreatAsFriendlyForTargetingAndDamage,
	CPED_CONFIG_FLAG_AllowBikeAlternateAnimations,
	CPED_CONFIG_FLAG_TreatAsFriendlyForTargetingAndDamageNonSynced,
	CPED_CONFIG_FLAG_UseLockpickVehicleEntryAnimations,
	CPED_CONFIG_FLAG_IgnoreInteriorCheckForSprinting,
	CPED_CONFIG_FLAG_SwatHeliSpawnWithinLastSpottedLocation,
	CPED_CONFIG_FLAG_DisableStartEngine,
	CPED_CONFIG_FLAG_IgnoreBeingOnFire,
	CPED_CONFIG_FLAG_DisableTurretOrRearSeatPreference,
	CPED_CONFIG_FLAG_DisableWantedHelicopterSpawning,
	CPED_CONFIG_FLAG_UseTargetPerceptionForCreatingAimedAtEvents,
	CPED_CONFIG_FLAG_DisableHomingMissileLockon,
	CPED_CONFIG_FLAG_ForceIgnoreMaxMeleeActiveSupportCombatants,
	CPED_CONFIG_FLAG_StayInDefensiveAreaWhenInVehicle,
	CPED_CONFIG_FLAG_DontShoutTargetPosition,
	CPED_CONFIG_FLAG_DisableHelmetArmor,
	CPED_CONFIG_FLAG_CreatedByConcealedPlayer,
	CPED_CONFIG_FLAG_PermanentlyDisablePotentialToBeWalkedIntoResponse,
	CPED_CONFIG_FLAG_PreventVehExitDueToInvalidWeapon,
	CPED_CONFIG_FLAG_IgnoreNetSessionFriendlyFireCheckForAllowDamage,
	CPED_CONFIG_FLAG_DontLeaveCombatIfTargetPlayerIsAttackedByPolice,
	CPED_CONFIG_FLAG_CheckLockedBeforeWarp,
	CPED_CONFIG_FLAG_DontShuffleInVehicleToMakeRoom,
	CPED_CONFIG_FLAG_GiveWeaponOnGetup,
	CPED_CONFIG_FLAG_DontHitVehicleWithProjectiles,
	CPED_CONFIG_FLAG_DisableForcedEntryForOpenVehiclesFromTryLockedDoor,
	CPED_CONFIG_FLAG_FiresDummyRockets,
	CPED_CONFIG_FLAG_PedIsArresting,
	CPED_CONFIG_FLAG_IsDecoyPed,
	CPED_CONFIG_FLAG_HasEstablishedDecoy,
	CPED_CONFIG_FLAG_BlockDispatchedHelicoptersFromLanding,
	CPED_CONFIG_FLAG_DontCryForHelpOnStun,
	CPED_CONFIG_FLAG_HitByTranqWeapon,
	CPED_CONFIG_FLAG_CanBeIncapacitated,
	CPED_CONFIG_FLAG_ForcedAimFromArrest,
};